/*
 * Tegra 11x SoC-specific mcerr code.
 *
 * Copyright (c) 2010-2014, NVIDIA Corporation. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

#include <linux/platform/tegra/mcerr.h>
#include <dt-bindings/memory/tegra-swgroup.h>

/*** Auto generated by `mcp.pl'. Do not modify! ***/

struct mc_client mc_clients[] = {
	client("ptc", "csr_ptcr", INVALID),
	client("dc", "csr_display0a", DC),
	client("dcb", "csr_display0ab", DCB),
	client("dc", "csr_display0b", DC),
	client("dcb", "csr_display0bb", DCB),
	client("dc", "csr_display0c", DC),
	client("dcb", "csr_display0cb", DCB),
	dummy_client,
	dummy_client,
	client("epp", "cbr_eppup", EPP),
	client("g2", "cbr_g2pr", G2),
	client("g2", "cbr_g2sr", G2),
	dummy_client,
	dummy_client,
	dummy_client,
	client("avpc", "csr_avpcarm7r", AVPC),
	client("dc", "csr_displayhc", DC),
	client("dcb", "csr_displayhcb", DCB),
	client("nv", "csr_fdcdrd", NV),
	client("nv", "csr_fdcdrd2", NV),
	client("g2", "csr_g2dr", G2),
	client("hda", "csr_hdar", HDA),
	client("hc", "csr_host1xdmar", HC),
	client("hc", "csr_host1xr", HC),
	client("nv", "csr_idxsrd", NV),
	dummy_client,
	dummy_client,
	dummy_client,
	client("msenc", "csr_msencsrd", MSENC),
	client("ppcs", "csr_ppcsahbdmar", PPCS),
	client("ppcs", "csr_ppcsahbslvr", PPCS),
	dummy_client,
	client("nv", "csr_texl2srd", NV),
	dummy_client,
	client("vde", "csr_vdebsevr", VDE),
	client("vde", "csr_vdember", VDE),
	client("vde", "csr_vdemcer", VDE),
	client("vde", "csr_vdetper", VDE),
	client("mpcorelp", "csr_mpcorelpr", INVALID),
	client("mpcore", "csr_mpcorer", INVALID),
	client("epp", "cbw_eppu", EPP),
	client("epp", "cbw_eppv", EPP),
	client("epp", "cbw_eppy", EPP),
	client("msenc", "csw_msencswr", MSENC),
	client("vi", "cbw_viwsb", VI),
	client("vi", "cbw_viwu", VI),
	client("vi", "cbw_viwv", VI),
	client("vi", "cbw_viwy", VI),
	client("g2", "ccw_g2dw", G2),
	dummy_client,
	client("avpc", "csw_avpcarm7w", AVPC),
	client("nv", "csw_fdcdwr", NV),
	client("nv", "csw_fdcdwr2", NV),
	client("hda", "csw_hdaw", HDA),
	client("hc", "csw_host1xw", HC),
	client("isp", "csw_ispw", ISP),
	client("mpcorelp", "csw_mpcorelpw", INVALID),
	client("mpcore", "csw_mpcorew", INVALID),
	dummy_client,
	client("ppcs", "csw_ppcsahbdmaw", PPCS),
	client("ppcs", "csw_ppcsahbslvw", PPCS),
	dummy_client,
	client("vde", "csw_vdebsevw", VDE),
	client("vde", "csw_vdedbgw", VDE),
	client("vde", "csw_vdembew", VDE),
	client("vde", "csw_vdetpmw", VDE),
	dummy_client,
	dummy_client,
	dummy_client,
	dummy_client,
	dummy_client,
	dummy_client,
	dummy_client,
	dummy_client,
	client("xusb_host", "csr_xusb_hostr", XUSB_HOST),
	client("xusb_host", "csw_xusb_hostw", XUSB_HOST),
	client("xusb_dev", "csr_xusb_devr", XUSB_DEV),
	client("xusb_dev", "csw_xusb_devw", XUSB_DEV),
	client("nv", "csw_fdcdwr3", NV),
	client("nv", "csr_fdcdrd3", NV),
	client("nv", "csw_fdcdwr4", NV),
	client("nv", "csr_fdcdrd4", NV),
	client("emucif", "csr_emucifr", INVALID),
	client("emucif", "csw_emucifw", INVALID),
	client("tsec", "csr_tsecsrd", TSEC),
	client("tsec", "csw_tsecswr", TSEC),
};
int mc_client_last = ARRAY_SIZE(mc_clients) - 1;
/*** Done. ***/

static const char *t114_intr_info[] = {
	NULL,		/* Bit 0 */
	NULL,
	NULL,
	NULL,
	NULL,		/* Bit 4 */
	NULL,
	"decerr-emem",
	NULL,
	"secerr",	/* Bit 8 */
	"arb-emem",
	"smmu-err",
	"apb_err",
	"decerr-vpr",	/* Bit 12 */
	"decerr-sec",
	NULL,
	NULL,
	"decerr-mts",	/* Bit 16 */
	NULL,
	NULL,
	NULL,
	NULL,		/* Bit 20 */
	NULL,
	NULL,
	NULL,
	NULL,		/* Bit 24 */
	NULL,
	NULL,
	NULL,
	NULL,		/* Bit 28 */
	NULL,
	NULL,
	NULL,
};

/*
 * Set up chip specific functions and data for handling this particular chip's
 * error decoding and logging.
 */
void mcerr_chip_specific_setup(struct mcerr_chip_specific *spec)
{
	spec->nr_clients = ARRAY_SIZE(mc_clients);
	spec->intr_descriptions = t114_intr_info;
	return;
}
